--Average Order Values (AOV)
WITH MONTHLY_SALES AS(
SELECT 
YEAR(ORDERPURCHASE_TIMESTAMP) AS SALES_YEAR,
MONTH(ORDERPURCHASE_TIMESTAMP) AS SALES_MONTH,
COUNT(ORDERID) AS TOTAL_ORDERS,
COUNT(DISTINCT CUSTOMER_UNIQID) AS UNIQ_CUSTOMERS,
SUM(PRICE) AS TOTAL_REVENUE
FROM  order_customer
GROUP BY YEAR(ORDERPURCHASE_TIMESTAMP), 
MONTH(ORDERPURCHASE_TIMESTAMP)
)

SELECT
SALES_YEAR,
SALES_MONTH, 
UNIQ_CUSTOMERS,
TOTAL_ORDERS,
TOTAL_REVENUE,
(TOTAL_REVENUE/TOTAL_ORDERS) AS AOV
FROM MONTHLY_SALES
ORDER BY TOTAL_REVENUE DESC