--Pareto
WITH CUSTOMERSTATUS AS(
SELECT
CUSTOMER_UNIQID,
COUNT (ORDERID) AS ORDER_COUNT,
SUM(PRICE) AS TOTAL_SPEND
FROM order_customer
GROUP BY CUSTOMER_UNIQID
),
CUSTOMER_SEGMENT AS(
SELECT 
CUSTOMER_UNIQID,
ORDER_COUNT,
TOTAL_SPEND,
CASE
WHEN ORDER_COUNT >=3 AND TOTAL_SPEND > 15000 THEN 'VIP'
WHEN ORDER_COUNT >=3 AND TOTAL_SPEND <= 15000 THEN 'LOYAL BUT LOW SPENDER'
WHEN ORDER_COUNT <5 AND TOTAL_SPEND > 10000 THEN 'NEW BUT HIGH POTENTIAL'
ELSE 'STANDART'
END AS CUSTOMER_SEGMENT
FROM CUSTOMERSTATUS
)
SELECT CUSTOMER_SEGMENT,
COUNT (*) AS CUSTOMER_COUNT,
SUM (TOTAL_SPEND) AS TOTAL_REVENUE,
ROUND(SUM(TOTAL_SPEND)*100.00/SUM (SUM(TOTAL_SPEND)) OVER (),2) AS REVENUE_PERCENTAGE
FROM CUSTOMER_SEGMENT
GROUP BY CUSTOMER_SEGMENT 
ORDER BY TOTAL_REVENUE DESC