
WITH CUSTOMERSTATUS AS (
    SELECT
        CUSTOMER_UNIQID,
        COUNT(ORDERID) AS ORDER_COUNT,
        SUM(PRICE) AS TOTAL_SPEND,
        MAX(ORDERPURCHASE_TIMESTAMP) AS LAST_ORDER_DATE 
    FROM order_customer
    GROUP BY CUSTOMER_UNIQID
),
VIP_LIST AS (
    SELECT * FROM CUSTOMERSTATUS
    WHERE ORDER_COUNT >= 3 AND TOTAL_SPEND > 15000
)
SELECT 
    CUSTOMER_UNIQID,
    TOTAL_SPEND,
    LAST_ORDER_DATE,
    DATEDIFF(day, LAST_ORDER_DATE, '2018-08-31') AS DAYS_SINCE_LAST_ORDER,
    CASE 
        WHEN DATEDIFF(day, LAST_ORDER_DATE, '2018-08-31') > 180 THEN 'AT RISK CUSTOMERS'
        WHEN DATEDIFF(day, LAST_ORDER_DATE, '2018-08-31') BETWEEN 90 AND 180 THEN 'CHURN RISK CUSTOMERS'
        ELSE 'ACTIVE CUSTOMERS'
    END AS CHURN_STATUS
FROM VIP_LIST
ORDER BY DAYS_SINCE_LAST_ORDER DESC