--RFM (Recency, Frequency, Monetary)
WITH CUSTOMERSTATUS AS(
SELECT
CUSTOMER_UNIQID,
COUNT (ORDERID) AS ORDER_COUNT,
SUM(PRICE) AS TOTAL_SPEND
FROM order_customer
GROUP BY CUSTOMER_UNIQID
)
SELECT 
CUSTOMER_UNIQID,
ORDER_COUNT,
TOTAL_SPEND,
CASE
WHEN ORDER_COUNT >=3 AND TOTAL_SPEND > 15000 THEN 'VIP'
WHEN ORDER_COUNT >=3 AND TOTAL_SPEND <= 15000 THEN 'LOYAL BUT LOW SPENDER'
WHEN ORDER_COUNT <5 AND TOTAL_SPEND > 10000 THEN 'NEW BUT HIGH POTENTIAL'
ELSE 'STANDART'
END AS CUSTOMER_SEGMENT
FROM CUSTOMERSTATUS
ORDER BY CUSTOMER_SEGMENT DESC
