WITH MONTHLY_SALES AS(
SELECT 
YEAR(ORDERPURCHASE_TIMESTAMP) AS SALES_YEAR,
MONTH(ORDERPURCHASE_TIMESTAMP) AS SALES_MONTH,
COUNT(ORDERID) AS TOTAL_ORDERS,
SUM(PRICE) AS TOTAL_REVENUE
FROM  order_customer
GROUP BY YEAR(ORDERPURCHASE_TIMESTAMP), 
MONTH(ORDERPURCHASE_TIMESTAMP)
)

SELECT TOP 1
SALES_YEAR,
SALES_MONTH, 
FORMAT(TOTAL_REVENUE, 'N', 'tr-TR') AS MAX_REVENUE
FROM MONTHLY_SALES
ORDER BY TOTAL_REVENUE DESC